name: Swift

on:
  push:
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate_code_coverage:
    runs-on: macos-arm
    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
    - name: Build & Run tests
      run: swift test --enable-code-coverage

  build_and_test_spm_mac:
    runs-on: macos-arm
    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
    - name: Build & Run tests
      run: swift test

  build_and_test_ios:
    runs-on: macos-arm
    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
    - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: /Users/runner/Library/Developer/Xcode/DerivedData/**/SourcePackages/checkouts
        key: ${{ runner.os }}-spm-ios-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-ios-
    - run: xcodebuild -scheme Sovran-Package test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 17'

  build_and_test_tvos:
    runs-on: macos-arm
    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
    - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: /Users/runner/Library/Developer/Xcode/DerivedData/**/SourcePackages/checkouts
        key: ${{ runner.os }}-spm-tvos-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-tvos-
    - run: xcodebuild -scheme Sovran-Package test -sdk appletvsimulator -destination 'platform=tvOS Simulator,name=Apple TV'

  build_and_test_watchos:
    runs-on: macos-arm
    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
    - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: /Users/runner/Library/Developer/Xcode/DerivedData/**/SourcePackages/checkouts
        key: ${{ runner.os }}-spm-watchos-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-watchos-
    - run: xcodebuild -scheme Sovran-Package test -sdk watchsimulator -destination 'platform=watchOS Simulator,name=Apple Watch Ultra 3 (49mm)'
