name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cancel_previous:
    runs-on: ubuntu-latest-large
    steps:
    - uses: styfle/cancel-workflow-action@a40b8845c0683271d9f53dfcb887a7e181d3918b  # 0.9.1
      with:
        workflow_id: ${{ github.event.workflow.id }}

  generate_code_coverage:
    needs: cancel_previous
    runs-on: macos-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90  # v1
      with:
        xcode-version: latest-stable
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5  # v2
    - name: Build & Run tests
      run: swift test --enable-code-coverage
    - name: Convert coverage report
      run: xcrun llvm-cov export -format="lcov" .build/debug/SovranPackageTests.xctest/Contents/MacOS/SovranPackageTests -instr-profile .build/debug/codecov/default.profdata > coverage.lcov
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@e0b68c6749509c5f83f984dd99a76a1c1a231044  # v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: segmentio/Sovran-Swift
        
  build_and_test_spm_mac:
    needs: cancel_previous
    runs-on: macos-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90  # v1
      with:
        xcode-version: latest-stable
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5  # v2
    - name: Build & Run tests
      run: swift test
      
  build_and_test_spm_linux:
    needs: cancel_previous
    runs-on: ubuntu-latest-large
    steps:
    - uses: fwal/setup-swift@bc791cf26355e933efee44da402ca4c8887fca3a  # v1.21.0
      with:
        swift-version: "5.7.2"
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5  # v2
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test --enable-test-discovery
      
  build_and_test_ios:
    needs: cancel_previous
    runs-on: macos-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90  # v1
      with:
        xcode-version: latest-stable
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5  # v2
    - uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace  # v2
      with:
        path: /Users/runner/Library/Developer/Xcode/DerivedData/**/SourcePackages/checkouts
        key: ${{ runner.os }}-spm-ios-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-ios-
    - run: xcodebuild -scheme Sovran-Package test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11'
    
  build_and_test_tvos:
    needs: cancel_previous
    runs-on: macos-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90  # v1
      with:
        xcode-version: latest-stable
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5  # v2
    - uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace  # v2
      with:
        path: /Users/runner/Library/Developer/Xcode/DerivedData/**/SourcePackages/checkouts
        key: ${{ runner.os }}-spm-tvos-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-tvos-
    - run: xcodebuild -scheme Sovran-Package test -sdk appletvsimulator -destination 'platform=tvOS Simulator,name=Apple TV'
  
  build_and_test_watchos:
    needs: cancel_previous
    runs-on: macos-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90  # v1
      with:
        xcode-version: latest-stable
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5  # v2
    - uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace  # v2
      with:
        path: /Users/runner/Library/Developer/Xcode/DerivedData/**/SourcePackages/checkouts
        key: ${{ runner.os }}-spm-watchos-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-watchos-
    - run: xcodebuild -scheme Sovran-Package test -sdk watchsimulator -destination 'platform=watchOS Simulator,name=Apple Watch Series 8 (45mm)'
